mov   eax, 0
mov   1a, eax
mov   eax, d
sub   eax, i
mov   _temp_14, eax
mov   eax, _temp_14
mov   d, eax
mov   eax, 5
mov   d, eax
mov   eax, 55
add   eax, 2
mov   _temp_13, eax
mov   eax, d
add   eax, 1
mov   _temp_12, eax
mov   eax, 2
mov   i, eax
mov   eax, 3
mov   x2, eax
mov   eax, 2
mov   n, eax
mov   eax, _temp_10
mov   i, eax
mov   eax, _temp_9
mov   d, eax
mov   eax, i
mov   x2, eax
mov   eax, 1
mov   n, eax
mov   eax, _temp_8
mov   i, eax
mov   eax, d
mov   x2, eax
mov   eax, d
mov   n, eax
mov   eax, _temp_7
mov   d, eax
mov   eax, a
add   eax, 1
mov   _temp_5, eax
mov   eax, _temp_5
mov   a, eax
mov   eax, x
add   eax, n
mov   _temp_0, eax
